models/TST: Fix d_model divisible assertion
Follow the 050_models.TSTPlus.ipynb implementation and make sure we actually
assert what we say we assert on this line. This commit breaks the inline test
where d_model is 128 and n_heads is 3, see below.

```
AssertionError in /home/anders/dev/ml/tsai/nbs/049_models.TST.ipynb:
===========================================================================

While Executing Cell #13:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[1], line 2
      1 t = torch.rand(16, 50, 128)
----> 2 output = _TSTEncoderLayer(q_len=50, d_model=128, n_heads=3, d_k=None, d_v=None, d_ff=512, dropout=0.1, activation='gelu')(t)
      3 output.shape

File ~/anaconda3/envs/tsai_dev/lib/python3.9/site-packages/fastcore/meta.py:40, in PrePostInitMeta.__call__(cls, *args, **kwargs)
     38 if type(res)==cls:
     39     if hasattr(res,'__pre_init__'): res.__pre_init__(*args,**kwargs)
---> 40     res.__init__(*args,**kwargs)
     41     if hasattr(res,'__post_init__'): res.__post_init__(*args,**kwargs)
     42 return res

Cell In[1], line 11, in _TSTEncoderLayer.__init__(self, q_len, d_model, n_heads, d_k, d_v, d_ff, dropout, activation)
      8 def __init__(self, q_len:int, d_model:int, n_heads:int, d_k:Optional[int]=None, d_v:Optional[int]=None, d_ff:int=256, dropout:float=0.1,
      9              activation:str="gelu"):
---> 11     assert not d_model%n_heads, f"d_model ({d_model}) must be divisible by n_heads ({n_heads})"
     12     d_k = ifnone(d_k, d_model // n_heads)
     13     d_v = ifnone(d_v, d_model // n_heads)

AssertionError: d_model (128) must be divisible by n_heads (3)
```